version: '3.8'

services:
  project_db:
    container_name: project_db
    image: postgres:13.0-alpine
    volumes:
      - project_data:/var/lib/postgresql/data/
    env_file:
      - .db.env
    ports:
      - "5433:5432"
  project_django:
    container_name: project_django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - project_db

volumes:
  project_data:
